export const demoBanners = [
  {
    id: 'demo-banner-1',
    title: 'Your next match starts here',
    description: 'Reserve premium courts in just a few clicks.',
    imageUrl: '/hero-bg.jpg',
    linkUrl: '/search',
  },
  {
    id: 'demo-banner-2',
    title: 'Play more. Book smarter.',
    description: 'Find great courts and sports facilities near you.',
    imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=1200&h=600&fit=crop',
    linkUrl: '/venues',
  },
];

export const demoVenues = [
  // ─── Ahmedabad ────────────────────────────────────────────────────────────────
  {
    id: 'demo-venue-arena',
    name: 'Sabarmati Sports Arena',
    description: 'A bright, modern indoor sports centre near Sabarmati for serious practice and friendly matches.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    rating: 4.8,
    totalReviews: 128,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20indoor%20badminton%20court%20with%20wooden%20flooring%20and%20green%20lines%2C%20bright%20LED%20ceiling%20lights%2C%20sports%20venue&image_size=landscape_4_3', caption: 'Indoor badminton court in Ahmedabad' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 450 },
      { sportType: 'BASKETBALL', pricePerHour: 900 },
    ],
  },
  {
    id: 'demo-venue-serve',
    name: 'Sardar Patel Tennis Club',
    description: 'Outdoor tennis courts in Navrangpura with evening lighting and coaching support.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    rating: 4.7,
    totalReviews: 94,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Outdoor%20clay%20tennis%20court%20with%20white%20lines%20and%20net%2C%20surrounded%20by%20green%20trees%20on%20sunny%20day&image_size=landscape_4_3', caption: 'Outdoor tennis court in Ahmedabad' }],
    courts: [{ sportType: 'TENNIS', pricePerHour: 700 }],
  },
  {
    id: 'demo-venue-kickoff',
    name: 'Kankaria Football Turf',
    description: 'Five-a-side turf near Kankaria Lake with fast booking and floodlit evening slots.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    rating: 4.6,
    totalReviews: 76,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Artificial%20green%20grass%20football%20turf%20court%20with%20white%20markings%2C%20floodlights%2C%20outdoor%20sports&image_size=landscape_4_3', caption: 'Football turf in Ahmedabad' }],
    courts: [{ sportType: 'FOOTBALL', pricePerHour: 1200 }],
  },
  {
    id: 'demo-venue-smash',
    name: 'Prahlad Nagar Smash Studio',
    description: 'Comfortable Ahmedabad courts for badminton, table tennis, and compact group sessions.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    rating: 4.5,
    totalReviews: 61,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Professional%20indoor%20badminton%20courts%20with%20synthetic%20floor%20and%20overhead%20LED%20lighting%20system&image_size=landscape_4_3', caption: 'Badminton court in Ahmedabad' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 350 },
      { sportType: 'TABLE_TENNIS', pricePerHour: 300 },
    ],
  },
  {
    id: 'demo-venue-amd-cricket',
    name: 'Motera Cricket Academy',
    description: 'Professional cricket nets and practice pitches near the world\'s largest cricket stadium.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    rating: 4.9,
    totalReviews: 210,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Cricket%20practice%20nets%20with%20green%20astro%20turf%20and%20batting%20pitch%2C%20outdoor%20sports%20academy&image_size=landscape_4_3', caption: 'Cricket nets in Ahmedabad' }],
    courts: [
      { sportType: 'CRICKET', pricePerHour: 800 },
      { sportType: 'FOOTBALL', pricePerHour: 1000 },
    ],
  },

  // ─── Surat ────────────────────────────────────────────────────────────────────
  {
    id: 'demo-venue-surat-diamond',
    name: 'Diamond City Sports Hub',
    description: 'Multi-sport facility in the heart of Surat offering world-class courts and coaching.',
    city: 'Surat',
    state: 'Gujarat',
    rating: 4.7,
    totalReviews: 143,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20multi%20sport%20indoor%20complex%20with%20basketball%20and%20badminton%20courts%2C%20view%20from%20above&image_size=landscape_4_3', caption: 'Multi-sport facility in Surat' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 400 },
      { sportType: 'SQUASH', pricePerHour: 500 },
    ],
  },
  {
    id: 'demo-venue-surat-tapi',
    name: 'Tapi Riverside Tennis Club',
    description: 'Scenic outdoor tennis courts along the Tapi riverfront with evening floodlights.',
    city: 'Surat',
    state: 'Gujarat',
    rating: 4.5,
    totalReviews: 87,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Hard%20court%20tennis%20facility%20with%20blue%20surface%20and%20white%20lines%2C%20stadium%20seating%2C%20sunny%20day&image_size=landscape_4_3', caption: 'Tennis courts in Surat' }],
    courts: [{ sportType: 'TENNIS', pricePerHour: 650 }],
  },
  {
    id: 'demo-venue-surat-athwa',
    name: 'Athwa Football Arena',
    description: 'Premium synthetic turf in Athwa Lines with covered seating and locker rooms.',
    city: 'Surat',
    state: 'Gujarat',
    rating: 4.6,
    totalReviews: 112,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Artificial%20green%20grass%20football%20turf%20court%20with%20white%20markings%2C%20floodlights%2C%20outdoor%20sports&image_size=landscape_4_3', caption: 'Football turf in Surat' }],
    courts: [
      { sportType: 'FOOTBALL', pricePerHour: 1100 },
      { sportType: 'CRICKET', pricePerHour: 750 },
    ],
  },
  {
    id: 'demo-venue-surat-vesu',
    name: 'Vesu Sports Complex',
    description: 'Modern sports complex in Vesu with badminton, basketball and gym facilities.',
    city: 'Surat',
    state: 'Gujarat',
    rating: 4.4,
    totalReviews: 68,
    venueType: 'HYBRID',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Large%20indoor%20sports%20complex%20building%20with%20multiple%20courts%20for%20basketball%20and%20volleyball%2C%20modern%20architecture&image_size=landscape_4_3', caption: 'Sports complex in Surat' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 380 },
      { sportType: 'BASKETBALL', pricePerHour: 850 },
    ],
  },
  {
    id: 'demo-venue-surat-adajan',
    name: 'Adajan Squash & Fitness',
    description: 'Dedicated squash courts with air conditioning and certified coaching in Adajan.',
    city: 'Surat',
    state: 'Gujarat',
    rating: 4.3,
    totalReviews: 54,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20indoor%20badminton%20court%20with%20wooden%20flooring%20and%20green%20lines%2C%20bright%20LED%20ceiling%20lights%2C%20sports%20venue&image_size=landscape_4_3', caption: 'Squash courts in Surat' }],
    courts: [
      { sportType: 'SQUASH', pricePerHour: 480 },
      { sportType: 'TABLE_TENNIS', pricePerHour: 280 },
    ],
  },

  // ─── Vadodara ─────────────────────────────────────────────────────────────────
  {
    id: 'demo-venue-vadodara-alkapuri',
    name: 'Alkapuri Cricket Ground',
    description: 'Full-size cricket ground with practice nets in the upscale Alkapuri area.',
    city: 'Vadodara',
    state: 'Gujarat',
    rating: 4.6,
    totalReviews: 109,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Cricket%20practice%20nets%20with%20green%20astro%20turf%20and%20batting%20pitch%2C%20outdoor%20sports%20academy&image_size=landscape_4_3', caption: 'Cricket ground in Vadodara' }],
    courts: [{ sportType: 'CRICKET', pricePerHour: 900 }],
  },
  {
    id: 'demo-venue-vadodara-race',
    name: 'Racecourse Football Hub',
    description: 'Five-a-side and seven-a-side football turfs near Vadodara Racecourse.',
    city: 'Vadodara',
    state: 'Gujarat',
    rating: 4.5,
    totalReviews: 83,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Artificial%20green%20grass%20football%20turf%20court%20with%20white%20markings%2C%20floodlights%2C%20outdoor%20sports&image_size=landscape_4_3', caption: 'Football turf in Vadodara' }],
    courts: [{ sportType: 'FOOTBALL', pricePerHour: 1050 }],
  },
  {
    id: 'demo-venue-vadodara-fatehgunj',
    name: 'Fatehgunj Indoor Arena',
    description: 'Air-conditioned indoor arena with courts for badminton, table tennis and basketball.',
    city: 'Vadodara',
    state: 'Gujarat',
    rating: 4.4,
    totalReviews: 72,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Professional%20indoor%20badminton%20courts%20with%20synthetic%20floor%20and%20overhead%20LED%20lighting%20system&image_size=landscape_4_3', caption: 'Indoor arena in Vadodara' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 400 },
      { sportType: 'TABLE_TENNIS', pricePerHour: 280 },
      { sportType: 'BASKETBALL', pricePerHour: 800 },
    ],
  },
  {
    id: 'demo-venue-vadodara-manjalpur',
    name: 'Manjalpur Multi-Sport Complex',
    description: 'Budget-friendly multi-sport facility in Manjalpur with excellent infrastructure.',
    city: 'Vadodara',
    state: 'Gujarat',
    rating: 4.2,
    totalReviews: 48,
    venueType: 'HYBRID',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20multi%20sport%20indoor%20complex%20with%20basketball%20and%20badminton%20courts%2C%20view%20from%20above&image_size=landscape_4_3', caption: 'Multi-sport complex in Vadodara' }],
    courts: [
      { sportType: 'VOLLEYBALL', pricePerHour: 350 },
      { sportType: 'BADMINTON', pricePerHour: 320 },
    ],
  },

  // ─── Rajkot ───────────────────────────────────────────────────────────────────
  {
    id: 'demo-venue-rajkot-khedut',
    name: 'Khedut Sports Academy',
    description: 'Popular Rajkot academy offering cricket nets, football turf, and badminton courts.',
    city: 'Rajkot',
    state: 'Gujarat',
    rating: 4.6,
    totalReviews: 134,
    venueType: 'HYBRID',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Cricket%20practice%20nets%20with%20green%20astro%20turf%20and%20batting%20pitch%2C%20outdoor%20sports%20academy&image_size=landscape_4_3', caption: 'Sports academy in Rajkot' }],
    courts: [
      { sportType: 'CRICKET', pricePerHour: 750 },
      { sportType: 'BADMINTON', pricePerHour: 380 },
    ],
  },
  {
    id: 'demo-venue-rajkot-yagnik',
    name: 'Yagnik Road Tennis Hub',
    description: 'Centrally located tennis club with 4 outdoor courts and evening lights.',
    city: 'Rajkot',
    state: 'Gujarat',
    rating: 4.4,
    totalReviews: 91,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Hard%20court%20tennis%20facility%20with%20blue%20surface%20and%20white%20lines%2C%20stadium%20seating%2C%20sunny%20day&image_size=landscape_4_3', caption: 'Tennis courts in Rajkot' }],
    courts: [{ sportType: 'TENNIS', pricePerHour: 600 }],
  },
  {
    id: 'demo-venue-rajkot-mavdi',
    name: 'Mavdi Football Club',
    description: 'Well-maintained synthetic turf in Mavdi with locker rooms and refreshment area.',
    city: 'Rajkot',
    state: 'Gujarat',
    rating: 4.5,
    totalReviews: 77,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Artificial%20green%20grass%20football%20turf%20court%20with%20white%20markings%2C%20floodlights%2C%20outdoor%20sports&image_size=landscape_4_3', caption: 'Football club in Rajkot' }],
    courts: [{ sportType: 'FOOTBALL', pricePerHour: 1000 }],
  },
  {
    id: 'demo-venue-rajkot-kalawad',
    name: 'Kalawad Road Indoor Sports',
    description: 'Modern indoor facility with badminton, squash, and table tennis under one roof.',
    city: 'Rajkot',
    state: 'Gujarat',
    rating: 4.3,
    totalReviews: 59,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20indoor%20badminton%20court%20with%20wooden%20flooring%20and%20green%20lines%2C%20bright%20LED%20ceiling%20lights%2C%20sports%20venue&image_size=landscape_4_3', caption: 'Indoor sports in Rajkot' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 360 },
      { sportType: 'SQUASH', pricePerHour: 440 },
      { sportType: 'TABLE_TENNIS', pricePerHour: 250 },
    ],
  },
  {
    id: 'demo-venue-rajkot-kothari',
    name: 'Kothari Volleyball Arena',
    description: 'Purpose-built volleyball courts with sand and hard surfaces, popular with college teams.',
    city: 'Rajkot',
    state: 'Gujarat',
    rating: 4.2,
    totalReviews: 41,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Heritage%20sports%20club%20building%20with%20tennis%20courts%20and%20lush%20green%20gardens%2C%20premium%20facility&image_size=landscape_4_3', caption: 'Volleyball arena in Rajkot' }],
    courts: [{ sportType: 'VOLLEYBALL', pricePerHour: 400 }],
  },

  // ─── Gandhinagar ──────────────────────────────────────────────────────────────
  {
    id: 'demo-venue-gandhinagar-capital',
    name: 'Capital City Sports Complex',
    description: 'Government-approved sports complex in Gandhinagar Sector 12 with Olympic-standard facilities.',
    city: 'Gandhinagar',
    state: 'Gujarat',
    rating: 4.7,
    totalReviews: 152,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Large%20indoor%20sports%20complex%20building%20with%20multiple%20courts%20for%20basketball%20and%20volleyball%2C%20modern%20architecture&image_size=landscape_4_3', caption: 'Sports complex in Gandhinagar' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 420 },
      { sportType: 'BASKETBALL', pricePerHour: 850 },
      { sportType: 'VOLLEYBALL', pricePerHour: 380 },
    ],
  },
  {
    id: 'demo-venue-gandhinagar-infocity',
    name: 'Infocity Cricket Ground',
    description: 'Premium cricket practice facility near the Infocity tech park, popular with IT professionals.',
    city: 'Gandhinagar',
    state: 'Gujarat',
    rating: 4.5,
    totalReviews: 89,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Cricket%20practice%20nets%20with%20green%20astro%20turf%20and%20batting%20pitch%2C%20outdoor%20sports%20academy&image_size=landscape_4_3', caption: 'Cricket ground in Gandhinagar' }],
    courts: [{ sportType: 'CRICKET', pricePerHour: 800 }],
  },
  {
    id: 'demo-venue-gandhinagar-gift',
    name: 'GIFT City Tennis Centre',
    description: 'Upscale tennis centre in the GIFT City corridor with state-of-the-art clay courts.',
    city: 'Gandhinagar',
    state: 'Gujarat',
    rating: 4.6,
    totalReviews: 74,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Hard%20court%20tennis%20facility%20with%20blue%20surface%20and%20white%20lines%2C%20stadium%20seating%2C%20sunny%20day&image_size=landscape_4_3', caption: 'Tennis centre in Gandhinagar' }],
    courts: [{ sportType: 'TENNIS', pricePerHour: 700 }],
  },
  {
    id: 'demo-venue-gandhinagar-sector7',
    name: 'Sector 7 Football Turf',
    description: 'Family-friendly football turf in residential Sector 7 with weekend coaching clinics.',
    city: 'Gandhinagar',
    state: 'Gujarat',
    rating: 4.3,
    totalReviews: 55,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Artificial%20green%20grass%20football%20turf%20court%20with%20white%20markings%2C%20floodlights%2C%20outdoor%20sports&image_size=landscape_4_3', caption: 'Football turf in Gandhinagar' }],
    courts: [{ sportType: 'FOOTBALL', pricePerHour: 950 }],
  },
  {
    id: 'demo-venue-gandhinagar-akshardham',
    name: 'Akshardham Sports Village',
    description: 'Large outdoor sports village near Akshardham with cricket, football and athletics track.',
    city: 'Gandhinagar',
    state: 'Gujarat',
    rating: 4.4,
    totalReviews: 63,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Heritage%20sports%20club%20building%20with%20tennis%20courts%20and%20lush%20green%20gardens%2C%20premium%20facility&image_size=landscape_4_3', caption: 'Sports village in Gandhinagar' }],
    courts: [
      { sportType: 'CRICKET', pricePerHour: 750 },
      { sportType: 'FOOTBALL', pricePerHour: 900 },
    ],
  },

  // ─── Jamnagar ─────────────────────────────────────────────────────────────────
  {
    id: 'demo-venue-jamnagar-ranjit',
    name: 'Ranjit Sagar Sports Club',
    description: 'Established sports club near Ranjit Sagar Lake with badminton and swimming.',
    city: 'Jamnagar',
    state: 'Gujarat',
    rating: 4.5,
    totalReviews: 98,
    venueType: 'HYBRID',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Large%20indoor%20sports%20complex%20building%20with%20multiple%20courts%20for%20basketball%20and%20volleyball%2C%20modern%20architecture&image_size=landscape_4_3', caption: 'Sports club in Jamnagar' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 390 },
      { sportType: 'SWIMMING', pricePerHour: 600 },
    ],
  },
  {
    id: 'demo-venue-jamnagar-bedi',
    name: 'Bedi Port Football Ground',
    description: 'Full-size football ground near Bedi Port, home to Jamnagar\'s amateur leagues.',
    city: 'Jamnagar',
    state: 'Gujarat',
    rating: 4.3,
    totalReviews: 67,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Artificial%20green%20grass%20football%20turf%20court%20with%20white%20markings%2C%20floodlights%2C%20outdoor%20sports&image_size=landscape_4_3', caption: 'Football ground in Jamnagar' }],
    courts: [{ sportType: 'FOOTBALL', pricePerHour: 900 }],
  },
  {
    id: 'demo-venue-jamnagar-digvijay',
    name: 'Digvijay Cricket Academy',
    description: 'Well-known cricket academy offering net practice and ground bookings.',
    city: 'Jamnagar',
    state: 'Gujarat',
    rating: 4.6,
    totalReviews: 115,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Cricket%20practice%20nets%20with%20green%20astro%20turf%20and%20batting%20pitch%2C%20outdoor%20sports%20academy&image_size=landscape_4_3', caption: 'Cricket academy in Jamnagar' }],
    courts: [{ sportType: 'CRICKET', pricePerHour: 700 }],
  },
  {
    id: 'demo-venue-jamnagar-shantinagar',
    name: 'Shantinagar Badminton Hall',
    description: 'Affordable badminton hall with 6 courts, open from early morning to late night.',
    city: 'Jamnagar',
    state: 'Gujarat',
    rating: 4.2,
    totalReviews: 44,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Professional%20indoor%20badminton%20courts%20with%20synthetic%20floor%20and%20overhead%20LED%20lighting%20system&image_size=landscape_4_3', caption: 'Badminton hall in Jamnagar' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 320 },
      { sportType: 'TABLE_TENNIS', pricePerHour: 240 },
    ],
  },
  {
    id: 'demo-venue-jamnagar-reliance',
    name: 'Reliance Sports Arena',
    description: 'Modern indoor arena with basketball and volleyball courts, part of a corporate township.',
    city: 'Jamnagar',
    state: 'Gujarat',
    rating: 4.4,
    totalReviews: 58,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20multi%20sport%20indoor%20complex%20with%20basketball%20and%20badminton%20courts%2C%20view%20from%20above&image_size=landscape_4_3', caption: 'Sports arena in Jamnagar' }],
    courts: [
      { sportType: 'BASKETBALL', pricePerHour: 800 },
      { sportType: 'VOLLEYBALL', pricePerHour: 420 },
    ],
  },

  // ─── Bhavnagar ────────────────────────────────────────────────────────────────
  {
    id: 'demo-venue-bhavnagar-victoria',
    name: 'Victoria Park Sports Ground',
    description: 'Iconic ground near Victoria Park offering cricket and football facilities since 1960.',
    city: 'Bhavnagar',
    state: 'Gujarat',
    rating: 4.5,
    totalReviews: 119,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Heritage%20sports%20club%20building%20with%20tennis%20courts%20and%20lush%20green%20gardens%2C%20premium%20facility&image_size=landscape_4_3', caption: 'Sports ground in Bhavnagar' }],
    courts: [
      { sportType: 'CRICKET', pricePerHour: 700 },
      { sportType: 'FOOTBALL', pricePerHour: 850 },
    ],
  },
  {
    id: 'demo-venue-bhavnagar-ghogha',
    name: 'Ghogha Road Badminton Club',
    description: 'Friendly neighbourhood badminton club on Ghogha Road with 4 synthetic courts.',
    city: 'Bhavnagar',
    state: 'Gujarat',
    rating: 4.3,
    totalReviews: 52,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20indoor%20badminton%20court%20with%20wooden%20flooring%20and%20green%20lines%2C%20bright%20LED%20ceiling%20lights%2C%20sports%20venue&image_size=landscape_4_3', caption: 'Badminton club in Bhavnagar' }],
    courts: [{ sportType: 'BADMINTON', pricePerHour: 350 }],
  },
  {
    id: 'demo-venue-bhavnagar-nilambag',
    name: 'Nilambag Tennis Courts',
    description: 'Historic tennis courts near Nilambag Palace with a heritage atmosphere.',
    city: 'Bhavnagar',
    state: 'Gujarat',
    rating: 4.4,
    totalReviews: 71,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Hard%20court%20tennis%20facility%20with%20blue%20surface%20and%20white%20lines%2C%20stadium%20seating%2C%20sunny%20day&image_size=landscape_4_3', caption: 'Tennis courts in Bhavnagar' }],
    courts: [{ sportType: 'TENNIS', pricePerHour: 580 }],
  },
  {
    id: 'demo-venue-bhavnagar-waghawadi',
    name: 'Waghawadi Multiplex Sports',
    description: 'Contemporary multi-sport venue on Waghawadi Road with squash and basketball courts.',
    city: 'Bhavnagar',
    state: 'Gujarat',
    rating: 4.2,
    totalReviews: 38,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Large%20indoor%20sports%20complex%20building%20with%20multiple%20courts%20for%20basketball%20and%20volleyball%2C%20modern%20architecture&image_size=landscape_4_3', caption: 'Multiplex sports in Bhavnagar' }],
    courts: [
      { sportType: 'SQUASH', pricePerHour: 450 },
      { sportType: 'BASKETBALL', pricePerHour: 780 },
    ],
  },
  {
    id: 'demo-venue-bhavnagar-kalanala',
    name: 'Kalanala Volleyball Park',
    description: 'Open-air volleyball park near Kalanala with sand courts, popular for evening games.',
    city: 'Bhavnagar',
    state: 'Gujarat',
    rating: 4.1,
    totalReviews: 29,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20multi%20sport%20indoor%20complex%20with%20basketball%20and%20badminton%20courts%2C%20view%20from%20above&image_size=landscape_4_3', caption: 'Volleyball park in Bhavnagar' }],
    courts: [{ sportType: 'VOLLEYBALL', pricePerHour: 320 }],
  },

  // ─── Anand ────────────────────────────────────────────────────────────────────
  {
    id: 'demo-venue-anand-charutar',
    name: 'Charutar Sports Complex',
    description: 'Premier sports complex affiliated with Charutar University, open to the public on weekends.',
    city: 'Anand',
    state: 'Gujarat',
    rating: 4.6,
    totalReviews: 103,
    venueType: 'HYBRID',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Modern%20multi%20sport%20indoor%20complex%20with%20basketball%20and%20badminton%20courts%2C%20view%20from%20above&image_size=landscape_4_3', caption: 'Sports complex in Anand' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 400 },
      { sportType: 'BASKETBALL', pricePerHour: 820 },
      { sportType: 'VOLLEYBALL', pricePerHour: 360 },
    ],
  },
  {
    id: 'demo-venue-anand-amul',
    name: 'Amul Cooperative Cricket Ground',
    description: 'Well-maintained cricket ground near the famous Amul dairy, with practice nets.',
    city: 'Anand',
    state: 'Gujarat',
    rating: 4.4,
    totalReviews: 78,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Cricket%20practice%20nets%20with%20green%20astro%20turf%20and%20batting%20pitch%2C%20outdoor%20sports%20academy&image_size=landscape_4_3', caption: 'Cricket ground in Anand' }],
    courts: [{ sportType: 'CRICKET', pricePerHour: 680 }],
  },
  {
    id: 'demo-venue-anand-vallabh',
    name: 'Vallabh Vidyanagar Tennis Club',
    description: 'Accessible tennis club near Vallabh Vidyanagar with four hard courts and coaching.',
    city: 'Anand',
    state: 'Gujarat',
    rating: 4.3,
    totalReviews: 61,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Hard%20court%20tennis%20facility%20with%20blue%20surface%20and%20white%20lines%2C%20stadium%20seating%2C%20sunny%20day&image_size=landscape_4_3', caption: 'Tennis club in Anand' }],
    courts: [{ sportType: 'TENNIS', pricePerHour: 560 }],
  },
  {
    id: 'demo-venue-anand-karamsad',
    name: 'Karamsad Badminton Academy',
    description: 'Professional badminton academy in Karamsad with six synthetic courts and coaching staff.',
    city: 'Anand',
    state: 'Gujarat',
    rating: 4.5,
    totalReviews: 85,
    venueType: 'INDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Professional%20indoor%20badminton%20courts%20with%20synthetic%20floor%20and%20overhead%20LED%20lighting%20system&image_size=landscape_4_3', caption: 'Badminton academy in Anand' }],
    courts: [
      { sportType: 'BADMINTON', pricePerHour: 380 },
      { sportType: 'TABLE_TENNIS', pricePerHour: 260 },
    ],
  },
  {
    id: 'demo-venue-anand-petlad',
    name: 'Petlad Football Turf',
    description: 'Budget-friendly football turf on the outskirts of Anand near Petlad highway.',
    city: 'Anand',
    state: 'Gujarat',
    rating: 4.1,
    totalReviews: 34,
    venueType: 'OUTDOOR',
    photos: [{ url: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=Artificial%20green%20grass%20football%20turf%20court%20with%20white%20markings%2C%20floodlights%2C%20outdoor%20sports&image_size=landscape_4_3', caption: 'Football turf near Anand' }],
    courts: [{ sportType: 'FOOTBALL', pricePerHour: 880 }],
  },
];

export const demoSports = [
  'BADMINTON',
  'TENNIS',
  'FOOTBALL',
  'BASKETBALL',
].map((sportType) => {
  const facilities = demoVenues.filter((venue) => venue.courts.some((court) => court.sportType === sportType));
  const prices = facilities.flatMap((venue) => venue.courts.filter((court) => court.sportType === sportType).map((court) => court.pricePerHour));

  return {
    sportType,
    venueCount: facilities.length,
    averagePrice: Math.round(prices.reduce((sum, price) => sum + price, 0) / prices.length),
    facilities: facilities.map((venue) => ({
      id: venue.id,
      name: venue.name,
      city: venue.city,
      rating: venue.rating,
      photos: venue.photos.map(({ url }) => ({ url })),
    })),
  };
});

const categoryDefinitions = [
  ['Indoor Venues', 'Climate-controlled facilities for year-round play', (venue: typeof demoVenues[number]) => venue.venueType === 'INDOOR'],
  ['Outdoor Venues', 'Natural playing environments with fresh air', (venue: typeof demoVenues[number]) => venue.venueType === 'OUTDOOR'],
  ['Premium Venues', 'Top-rated facilities with excellent reviews', (venue: typeof demoVenues[number]) => (venue.rating ?? 0) >= 4.7],
  ['Budget-Friendly', 'Affordable options without compromising quality', (venue: typeof demoVenues[number]) => venue.courts.some((court) => court.pricePerHour <= 500)],
] as const;

export const demoCategories = categoryDefinitions.map(([title, description, matches]) => ({
  title,
  description,
  venues: demoVenues.filter(matches),
}));

export const demoCities = [...new Set(demoVenues.map((venue) => venue.city))].map((city) => {
  const venues = demoVenues.filter((venue) => venue.city === city);

  return {
    city,
    venueCount: venues.length,
    venues: venues.map((venue) => ({
      id: venue.id,
      name: venue.name,
      city: venue.city,
      rating: venue.rating,
      photos: venue.photos.map(({ url }) => ({ url })),
    })),
  };
});

const demoBookingVenue = demoVenues[0];
const demoBookingCourt = demoBookingVenue.courts[0];

export const demoBookings = [
  {
    id: 'demo-booking-confirmed',
    hashId: 1001,
    status: 'CONFIRMED',
    bookingDate: '2026-09-20',
    startTime: '10:00:00',
    endTime: '11:00:00',
    totalHours: 1,
    pricePerHour: demoBookingCourt.pricePerHour,
    totalAmount: demoBookingCourt.pricePerHour,
    platformFee: 13.5,
    tax: 83.43,
    finalAmount: 546.93,
    specialRequests: 'Please keep two rackets ready.',
    confirmedAt: '2026-09-14T08:30:00.000Z',
    cancelledAt: null,
    cancellationReason: null,
    completedAt: null,
    createdAt: '2026-09-14T08:25:00.000Z',
    updatedAt: '2026-09-14T08:30:00.000Z',
    facility: {
      id: demoBookingVenue.id,
      name: demoBookingVenue.name,
      address: 'Sabarmati Sports Arena, Ashram Road, Ahmedabad',
      city: demoBookingVenue.city,
      phone: '+91 98765 43210',
      rating: demoBookingVenue.rating,
      totalReviews: demoBookingVenue.totalReviews,
    },
    court: {
      id: 'demo-venue-arena-court-1',
      name: 'Badminton Court 1',
      sportType: demoBookingCourt.sportType,
      surface: 'Premium synthetic',
      capacity: 8,
      pricePerHour: demoBookingCourt.pricePerHour,
    },
    payment: { id: 'demo-payment-1001', amount: 450, platformFee: 13.5, tax: 83.43, totalAmount: 546.93, paymentMethod: 'CREDIT_CARD', status: 'COMPLETED', gatewayOrderId: 'demo-order-1001', transactionId: 'demo-txn-1001', paidAt: '2026-09-14T08:31:00.000Z', createdAt: '2026-09-14T08:30:00.000Z' },
    coupons: [],
  },
  {
    id: 'demo-booking-pending',
    hashId: 1002,
    status: 'PENDING',
    bookingDate: '2026-09-22',
    startTime: '18:00:00',
    endTime: '19:00:00',
    totalHours: 1,
    pricePerHour: 900,
    totalAmount: 900,
    platformFee: 27,
    tax: 166.86,
    finalAmount: 1093.86,
    specialRequests: null,
    confirmedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    completedAt: null,
    createdAt: '2026-09-14T07:10:00.000Z',
    updatedAt: '2026-09-14T07:10:00.000Z',
    facility: {
      id: 'demo-venue-kickoff',
      name: 'Kickoff Football Hub',
      address: 'Kankaria Football Turf, Maninagar, Ahmedabad',
      city: 'Ahmedabad',
      phone: '+91 98765 43210',
      rating: 4.6,
      totalReviews: 76,
    },
    court: { id: 'demo-venue-kickoff-court-1', name: 'Football Court 1', sportType: 'FOOTBALL', surface: 'Premium synthetic', capacity: 10, pricePerHour: 1200 },
    payment: { id: 'demo-payment-1002', amount: 900, platformFee: 27, tax: 166.86, totalAmount: 1093.86, paymentMethod: 'CREDIT_CARD', status: 'PENDING', gatewayOrderId: 'demo-order-1002', transactionId: undefined, paidAt: undefined, createdAt: '2026-09-14T07:10:00.000Z' },
    coupons: [],
  },
  {
    id: 'demo-booking-completed',
    hashId: 1003,
    status: 'COMPLETED',
    bookingDate: '2026-08-30',
    startTime: '07:00:00',
    endTime: '08:00:00',
    totalHours: 1,
    pricePerHour: 700,
    totalAmount: 700,
    platformFee: 21,
    tax: 129.78,
    finalAmount: 850.78,
    specialRequests: null,
    confirmedAt: '2026-08-29T09:00:00.000Z',
    cancelledAt: null,
    cancellationReason: null,
    completedAt: '2026-08-30T08:05:00.000Z',
    createdAt: '2026-08-29T08:55:00.000Z',
    updatedAt: '2026-08-30T08:05:00.000Z',
    facility: { id: 'demo-venue-serve', name: 'Sardar Patel Tennis Club', address: 'Navrangpura, Ahmedabad', city: 'Ahmedabad', phone: '+91 98765 43210', rating: 4.7, totalReviews: 94 },
    court: { id: 'demo-venue-serve-court-1', name: 'Tennis Court 1', sportType: 'TENNIS', surface: 'Premium synthetic', capacity: 4, pricePerHour: 700 },
    payment: { id: 'demo-payment-1003', amount: 700, platformFee: 21, tax: 129.78, totalAmount: 850.78, paymentMethod: 'CREDIT_CARD', status: 'COMPLETED', gatewayOrderId: 'demo-order-1003', transactionId: 'demo-txn-1003', paidAt: '2026-08-29T09:01:00.000Z', createdAt: '2026-08-29T09:00:00.000Z' },
    coupons: [],
  },
];
